Adding caching for organizations endpoint and ingesting export tokens.
JupiterOne/graph-rumble pull request #15
Opened 2022-02-24 21:44 UTC by zemberdotnet

# Description

Adding caching for `/account/orgs` endpoint and ingesting `Export Tokens` for use in future steps.

## Summary

### Cache Addition
This PR adds `orgCache` to the `APIClient`. Data from the `/account/orgs` endpoint is used in `verifyAuthentication`, `getExportTokens`, `getAccount`, and `getOrganizations`. To avoid calling this endpoint several times, the first response will be cached. At this time there is not need to expand caching to other parts of the client.

### Export Token Ingestion
The PR also ingests `Export Tokens`. These tokens are needed to access organization specific data from the `/export` API. `Export Tokens` are added to the config as the last step in `validateInvocation`. I chose to bring in the tokens at this point and not later because I thought that after `validateInvocation` we should know what the graph will and will not be able to ingest because of authorization. This will also allow future steps like `fetch-asset`, `fetch-services` and `fetch-wireless` to not have dependencies on the `organization` or `account` steps.

### Documentation Updates

Documentation in `jupiterone.md` and `development.md` has been updated with new instructions about generating `Export Tokens`.

## Type of change

Please leave any irrelevant options unchecked.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## Checklist

### General Development Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### Integration Development Checklist:

Please leave any irrelevant options unchecked.

- [X] I have checked for additional permissions required to call any new API
      endpoints, and have documented any additional permissions in
      `jupiterone.md`, where necessary.
- [ ] My changes properly paginate the target service provider's API
  - not available for Rumble API
- [ ] My changes properly handle rate limiting of the target service provider's
      API
  - not implemented yet
- [X] My new integration step is instrumented to execute in the correct order
      using `dependsOn`
- [X] I have referred to the
      [JupiterOne data model](https://github.com/JupiterOne/data-model/tree/main/src/schemas)
      to ensure that any new entities/relationships, and relevant properties,
      match the recommended model for this class of data
- [ ] I have updated the `CHANGELOG.md` file to describe my changes
- [X] When changes include modifications to existing graph data ingestion, I've
      reviewed all existing managed questions referencing the entities,
      relationships, and their property names, to ensure those questions still
      function with my changes.

2022-02-24 21:49 UTC, zemberdotnet commented on src/client.ts
> +          `An organization with name '${org.name}' and id '${org.id}' does not have export token. Asset, Services, and Wireless data for this organization won't be loaded. To generate an export token
I expect, but am not certain that an end user would see this message in their job. I cite `jupiterone.md` as the place to receive authorization instructions, but I also want to confirm that the user has access to and will know about `jupiterone.md`.

2022-02-24 21:50 UTC, zemberdotnet commented on src/config.ts
> +  config.exportTokens = await apiClient.getExportTokens();
The export tokens are added here we have validated authentication.

2022-02-25 04:25 UTC, mdaum requested changes

2022-02-25 04:25 UTC, mdaum commented on src/client.ts
> +          `An organization with name '${org.name}' and id '${org.id}' does not have export token. Asset, Services, and Wireless data for this organization won't be loaded. To generate an export token
You should be able to test this out in the UI in our dev env. In your private `integration-rumble` project, you'd link your local `graph-rumble` project, and then deploy to dev env. I could of sworn there were docs in our private repos or confluence on how to do just this but I could not find them after a bit of searching. Let's explore this together and get some documentation put together 👍

2022-02-25 04:25 UTC, mdaum commented on src/client.ts
> +  orgCache: { [key: string]: any } = {};
I think `any` can be changed to `RumbleOrganization` here. Would be better to do this.

2022-02-25 14:48 UTC, zemberdotnet commented on docs/jupiterone.md
> +  -
Woops. I think I overwrote the file. Thanks for spotting this. 👀

2022-02-25 18:47 UTC, zemberdotnet commented on src/client.ts
> +  orgCache: { [key: string]: any } = {};
Should be changed in the latest commits.

2022-02-28 15:47 UTC, merged