Int 2384 ingest rumble users
JupiterOne/graph-rumble pull request #7
Opened 2022-02-15 17:55 UTC by zemberdotnet

# Description

Ingest Rumble Users

## Summary

This PR adds the user step, makes updates to API Client to follow patterns, and makes slight changes to organization step to handle possible nulls in response.

The bulk of work went into deciding logic for setting roles on the `rumble_user_assigned_organization` relationship. Review for these decisions would be very helpful.

- API Client:
  - `getEntities` name change to `callApi`
  - Changed to using the default error message instead of overriding
     - Added optional response body to the end of the statusText for additional information if available
- User Steps
   - Created `fetchUserDetails`, `buildUserOrganizaitonRellationships`, and `buildAccountUserRelationships`
      - `buildUserOrganizationRelationships` sets two optional properties: `defaultRole` and `assignedRole`
         - Originally, I planned to derive a single `role` for each user based on Rumble role assignment logic. After feedback from Nick, I believe the best way is to set these two properties and not perform any manipulation. 
         - As best as I can tell, a user will always have a `defaultRole` unless they were the first user. In this case, the user will have their `client_admin` property set to `true`. Other users can be `client_admin`s and these users will also have admin access to all organizations regardless of assigned role.
- Organization Step
   - Handling `description` property from response possibly being `null`.

**Open Questions**
- Should a user with a derived role of `none` be assigned to an organization?
  - After the move away from deriving user roles, my initial response is no, but other thoughts are appreciated.
      

## Type of change

Please leave any irrelevant options unchecked.

- [X] Bug fix (non-breaking change which fixes an issue)
   - fixing possible `null` in organization step
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## Checklist

### General Development Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### Integration Development Checklist:

Please leave any irrelevant options unchecked.

- [X] I have checked for additional permissions required to call any new API
      endpoints, and have documented any additional permissions in
      `jupiterone.md`, where necessary.
- [ ] My changes properly paginate the target service provider's API
   - pagination not available, but `iterateEntity` pattern is followed
- [ ] My changes properly handle rate limiting of the target service provider's
      API
  - rate-limiting not created yet
- [X] My new integration step is instrumented to execute in the correct order
      using `dependsOn`
- [X] I have referred to the
      [JupiterOne data model](https://github.com/JupiterOne/data-model/tree/main/src/schemas)
      to ensure that any new entities/relationships, and relevant properties,
      match the recommended model for this class of data
- [X] I have updated the `CHANGELOG.md` file to describe my changes
- [ ] When changes include modifications to existing graph data ingestion, I've
      reviewed all existing managed questions referencing the entities,
      relationships, and their property names, to ensure those questions still
      function with my changes.
  - questions not created yet

2022-02-15 18:04 UTC, zemberdotnet commented on src/client.ts
> +          (err.response.body ? `\nBody: ${err.response.body.trim()}` : ''),
New error message should look like:
`Provider API failed at ${options.endpoint}: ${options.status} ${options.statusText}`, where `statusText` may have the additional message from `err.response.body`. Errors from Rumble usually contain a useful body describing the error like `{"error":"API Key Not Found"}`, so I thought this would be helpful.

2022-02-15 18:05 UTC, zemberdotnet commented on src/client.ts
> +    const organizations = await this.callApi({ url: endpoint });
`createRequest` and `getEntities` are rolled together into `callApi` where default config can be overridden by the `options` parameter.

2022-02-15 18:08 UTC, zemberdotnet commented on src/steps/users/index.test.ts
> +    expect(userOrganizationRelationships.length).toBe(18);
`userOrganizationRelationships` should create `userEntities.length` x `organizationEntities.length` relationships.

2022-02-15 19:37 UTC, adam-in-ict commented on src/steps/users/converter.ts
> +  };
Does Rumble have any concept of user roles or some kind of admin flag?  Depending on how it's structured, could have a separate rumble_role entity or could at a minimum add an admin boolean to Rumble users to let users query who in their organization is an admin.

Disregard if that data isn't available.😆

2022-02-16 17:00 UTC, zemberdotnet commented on src/steps/users/converter.ts
> +  };
Rumble does use roles to provide different access levels to users. There is a few different ways to set roles.
- a user can have their `client_admin` flag set to `true` and be a superuser for all organizations
- a user can have a `org_default_role` that provides a base level of access to all organizations
- a user can have a `org_role` for a specific organization that can extend but not reduce their level of access to a specific organization

J1 users can write queries like:
`FIND rumble_user WITH orgDefaultRole = ‘admin’ OR client_admin = true` to see admins for all organizations.
` FIND rumble_user THAT ASSIGNED as r rumble_org WHERE r.role = ‘admin’` to see users that are assigned admin for a certain organization.

Does that seem logical? Do you see any improvements?

2022-02-16 17:18 UTC, mdaum requested changes

2022-02-16 17:27 UTC, ndowmon commented on src/steps/users/index.ts
> +    id: Steps.BUILD_ACCOUNT_USER_RELATIONSHIPS,
I think this is good separation of concerns by following the **Build Child Relationships** pattern. https://github.com/JupiterOne/sdk/blob/main/docs/integrations/step-patterns.md#build-child-relationships-step-pattern

2022-02-16 17:47 UTC, ndowmon commented on src/steps/users/index.ts
> +  await jobState.iterateEntities(userFilter, async (userEntity) => {
I would strongly encourage the use of `getRawData` in order to get the user roles off of the `user` entity, rather than setting data in the `users` step by calling `await jobState.setData(user.id, user.org_roles);`:

I would also use `jobState.findEntity` to get the org entity rather than `jobState.iterateEntities`:

```ts
export async function buildUserOrganizationRelationships({
  jobState,
  logger,
}: IntegrationStepExecutionContext<IntegrationConfig>) {
  await jobState.iterateEntities({ _type: Entities.USER._type }, async (userEntity) => {
    const user = getRawData<RumbleUser>(userEntity);

    for (const [orgId, assignedRole] of Object.entries(user?.org_roles || {})) {
      const orgEntity = await jobState.findEntity(orgId);
      if (!orgEntity) {
        logger.warn(
          { userId: user?.id, assignedRole, orgId }, 
          'Could not locate orgId from user org_roles property'
        );
        continue;
      }

      await jobState.addRelationship(createDirectRelationship({
        from: userEntity,
        to: orgEntity,
        _class: RelationshipClass.ASSIGNED,
        properties: { assignedRole },
      }));
    }
  });
}
```

2022-02-16 18:05 UTC, ndowmon commented on src/steps/users/index.ts
> +    id: Steps.BUILD_USER_ORGANIZATION_RELATIONSHIPS,
> Note that when you call `jobState.iterateEntities`, you are actually iterating through an array of all your entities, regardless of type. The resulting set is determined by your filter you pass in.

Actually, this is not the case. See its [implementation here](https://github.com/JupiterOne/sdk/blob/main/packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts#L199):

```ts
  async iterateEntities<T extends Entity = Entity>(
    filter: GraphObjectFilter,
    iteratee: GraphObjectIteratee<T>,
  ) {
    await this.localGraphObjectStore.iterateEntities(filter, iteratee);

    await iterateEntityTypeIndex({
      type: filter._type,
      iteratee,
    });
  }
```

The `localGraphObjectStore` stores up to 500 entities in memory before being flushed to the job state, but [its implementation](https://github.com/JupiterOne/sdk/blob/main/packages/integration-sdk-runtime/src/storage/memory.ts#L134) uses a `entityTypeToKeysMap` in order to prevent us from iterating all of these 500 entities.

After entities are flushed to disk from the local store, the `iterateEntityTypeIndex()` call iterates only files for a given entity `_type`. You've probably seen how we store data on disk when running `yarn start`:

```
/.j1-integration
  /graph
  /index
    /relationships
    /entities
      /rumble_account
      /rumble_organization
      /rumble_user
        /e14672dd-52d6-419f-b151-7827c86833bf.json
```

So the `jobState.iterateEntities` bypasses all other entity types and goes straight to iterating the files at `./.j1-integration/index/entities/rumble_user`.

2022-02-16 18:09 UTC, ndowmon commented on src/steps/users/index.ts
> +                : undefined,
Since this is already on the `rumble_user` entity, I don't think it's necessary to include here. The user property can be the single source of truth for queries

2022-02-16 18:10 UTC, adam-in-ict commented on src/steps/users/converter.ts
> +  };
Based on the complexity of roles (having potentially a default role as well as potentially multiple other org-specific roles) my first thought is that it would make the most sense to have roles broken out into their own entities and then relationships to them (HAS_ROLE, HAS_DEFAULT_ROLE, something like that).

I think at a minimum including the client_admin flag as part of the user entity would be a great start and then you can decide when/if/how roles get ingested later as part of your ongoing larger discussions around the overall Rumble integration effort.

2022-02-16 18:17 UTC, ndowmon commented on src/steps/users/converter.ts
> +  };
> could at a minimum add an admin boolean to Rumble users to let users query who in their organization is an admin

I like @adam-in-ict 's thought here. We should add the standard `admin` property as an alias to `orgDefaultRole = 'admin' OR clientAdmin = true`, making these two queries equivalent:
- `FIND rumble_user WITH orgDefaultRole = 'admin' OR clientAdmin = true`
- `FIND rumble_user WITH admin = true`

In addition, I would add the following managed questions to this project:

**Which of my users are global admins?**
```
FIND rumble_user WITH admin = true
```

**Which of my users is an admin of any organization?**
```
FIND rumble_user as user THAT ASSIGNED as orgRole rumble_organization
WHERE user.admin = true OR orgRole.assignedRole = 'admin'
```

2022-02-16 19:04 UTC, mdaum commented on src/steps/users/index.ts
> +    id: Steps.BUILD_USER_ORGANIZATION_RELATIONSHIPS,
doh! don't know how I missed this. was not looking closely at the type index created. Thanks for correcting me here.

2022-02-16 19:10 UTC, mdaum commented on src/steps/users/index.ts
> +    await jobState.iterateEntities(orgFilter, async (orgEntity) => {
> we def don't want to do a `Θ(n^2)` operation here. let's fetch the organizations once outside this loop and store in memory. Then we can iterate on what should be a much smaller set of entities in this inner loop.

I actually really like @ndowmon [idea](https://github.com/JupiterOne/graph-rumble/pull/7#discussion_r808295190) here instead. Keep in its own step as you are currently, but use the raw data of the user to fetch individual org entities on an as-needed basis. More performant than holding all org entities in memory.

2022-02-16 19:11 UTC, mdaum commented on src/steps/users/index.ts
> +  await jobState.iterateEntities(userFilter, async (userEntity) => {
yea liking this a lot. go with this instead of my suggestion of fetching all orgs once from job state before continuing to iterate on what I mistakenly thought would be a smaller set of items.

2022-02-16 19:35 UTC, mdaum commented on src/steps/users/converter.ts
> +  };
This assumes that every user has a relationship with every org right?

2022-02-16 19:46 UTC, mdaum commented on src/steps/users/converter.ts
> +  };
If you don't have a relationship b/w every user and org,

`FIND rumble_user as user THAT ASSIGNED as orgRole rumble_organization
WHERE user.admin = true OR orgRole.assignedRole = 'admin'`
Union with
`FIND rumble_user WITH admin = true`
Would get you the actual answer to **Which of my users is an admin of any organization?**

If you do, then it is as simple as the query you posed earlier @ndowmon

2022-02-16 19:56 UTC, ndowmon commented on src/steps/users/converter.ts
> +  };
With optional traversal:
```
FIND rumble_user as user (THAT ASSIGNED as orgRole rumble_organization)?
WHERE user.admin = true OR orgRole.assignedRole = 'admin'
```

2022-02-16 21:43 UTC, zemberdotnet commented on src/client.ts
>          endpoint: err.response.requestUrl,
Updated to url in latest commit.

2022-02-16 21:44 UTC, zemberdotnet commented on src/steps/users/index.ts
> +    id: Steps.BUILD_ACCOUNT_USER_RELATIONSHIPS,
The `buildAccountUserRelationship` has been rolled into the `fetchUserDetails` in the latest commit.

2022-02-16 21:45 UTC, zemberdotnet commented on src/steps/users/index.ts
> +  await jobState.iterateEntities(userFilter, async (userEntity) => {
This pattern is now being used in the latest commit. Moved from all users having an `ASSIGNED` relationship to only those with roles in `org_roles` having an `ASSIGNED` relationship.

2022-02-18 20:31 UTC, mdaum reviewed
I'd love to see the graph picture!!

2022-02-18 20:31 UTC, mdaum commented on src/steps/users/index.test.ts
> +    expect(userAccountRelationships.length).toBeGreaterThan(0);
why is this no longer explicit?

2022-02-18 20:47 UTC, zemberdotnet commented on src/steps/users/index.test.ts
> +    expect(userAccountRelationships.length).toBeGreaterThan(0);
Changed this to `toBe(6)`

2022-02-18 21:50 UTC, mdaum approved these changes

2022-02-18 22:04 UTC, merged